VERSION=5
DOCKERUSER=soma5722

build:
	docker build -f Dockerfile -t finalproject-rest .
	docker tag finalproject-rest soma5722/finalproject-rest:latest
	docker push soma5722/finalproject-rest:latest
