apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: carbonfootprint-deployment
spec:
  selector:
    matchLabels:
      app: carbonfootprint
  replicas: 1
  template:
    metadata:
      labels:
        app: carbonfootprint
    spec:
      containers:
      - name: carbonfootprint
        image: soma5722/carbonfootprint:latest
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq
---
