VERSION=latest
DOCKERUSER=lincolnrychecky

build:
	docker build -f Dockerfile -t carbonfootprint .
	docker tag carbonfootprint soma5722/carbonfootprint:latest
	docker push soma5722/carbonfootprint:latest