apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: subscriber-manager-deployment
spec:
  selector:
    matchLabels:
      app: subscriber-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: subscriber-manager
    spec:
      containers:
      - name: subscriber-manager
        image: lincolnrychecky/subscriber-worker:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: REDIS_HOST
          value: redis
        - name: RABBITMQ_HOST
          value: rabbitmq
---
