kind: Service
apiVersion: v1
metadata:
  name: subscriber-svc
  labels:
   app: subscriber-manager
spec:
  spec:
  #type: NodePort
  selector:
    app: subscriber-manager
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---